### ISSUE TITLE
Missing copyright information for CC-BY artifacts

### ISSUE THREAD

**Issue by gibmat** [OpenRCT2/OpenSoundEffects#15]
The different sound effects that are licensed under CC-BY don't have any actual copyright/author information available. https://github.com/OpenRCT2/OpenSoundEffects/pull/7 partially addresses this; if those individuals didn't create the sounds themselves, the actual creator(s)/source(s) will need to be listed.

Proper attribution as per the terms of CC-BY is required before this library can be redistributed, such as in a Linux distro's packages of openrct2.

**Comment by Gymnasiast** [comment]
I merged #7 to begin with. We will add a table with attributions. Luckily, most samples were made by @karst anyway, so those should be straightforward.

**Comment by gibmat** [comment]
I was able to craft a decent enough copyright file to upload to Debian -- if there's issues getting it accepted, I'll open a new issue.

**Comment by Thaodan** [comment]
Just wondering why is opensfx license under CC-BY-SA-4.0 while the others e.g. title sequences and openmsfx are licensed under CC-BY-4.0.
